// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcg3RBYt-C8KRC7bU-mVtIZRuu06UkXM',
    appId: '1:822545969886:web:c83a8b101819adeefb484f',
    messagingSenderId: '822545969886',
    projectId: 'scanleno-37d42',
    authDomain: 'scanleno-37d42.firebaseapp.com',
    storageBucket: 'scanleno-37d42.firebasestorage.app',
    measurementId: 'G-QE0KFYYVQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiOy-s6IzH2g7x5nNVUinNbQk3X6UK78M',
    appId: '1:822545969886:android:6f7a593d6d273c36fb484f',
    messagingSenderId: '822545969886',
    projectId: 'scanleno-37d42',
    storageBucket: 'scanleno-37d42.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUeCREh9ejrMUmrpW37TleGaaTOYh77SI',
    appId: '1:822545969886:ios:2d2b53c6093f9003fb484f',
    messagingSenderId: '822545969886',
    projectId: 'scanleno-37d42',
    storageBucket: 'scanleno-37d42.firebasestorage.app',
    androidClientId: '822545969886-r2p4dqnc2ihp6l6km0h7cf3j2uo4itde.apps.googleusercontent.com',
    iosClientId: '822545969886-9v7gf0rhit387d6bkeru2mf8a1lbqfr5.apps.googleusercontent.com',
    iosBundleId: 'com.hotleno.scanleno',
  );
}
